---
- name: Install Tomcat
  hosts: WebCalcServers
  become: true
  vars:
    tomcat_admin_username: admin
    tomcat_admin_password: admin123
  
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
      when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

    - name: Install Java
      apt:
        name: openjdk-8-jre-headless
        state: present
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Download Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz"
        dest: /opt/

    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.54.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Configure Tomcat Users
      template:
        src: tomcat-users.xml.j2
        dest: /opt/apache-tomcat-9.0.54/conf/tomcat-users.xml
    
    - name: Start Tomcat Service
      shell: /opt/apache-tomcat-9.0.54/bin/startup.sh &
        name: tomcat
        enabled: yes
      when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

    - name: Start Tomcat Service
      systemd:
        name: tomcat
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

... 