---
- name: Clone web app repo
  hosts: WebCalcServers
  become: yes

  tasks:
  - name: Ensure System Packages Updated
    yum:
      update_cache: yes
    when: ansible_os_family == 'RedHat'

  - name: Ensure System Packages Updated
    apt:
      update_cache: yes
    when: ansible_os_family == 'Debian'
  
  - name: Install GIT
    yum:
     name: git
     state: present
    when: ansible_os_family == 'RedHat'

  - name: Install GIT
    apt:
     name: git
     state: present
    when: ansible_os_family == 'Debian'
 
  - name: Clone repository
    git:
     repo: https://github.com/Vivich007/Web3.git
     dest: /home/centos/Repo-dir
     version: main
     force: yes
    when: ansible_os_family == 'RedHat' 

  - name: Clone repository
    git:
     repo: https://github.com/Vivich007/Web3.git
     dest: /home/ubuntu/Repo-dir
     version: main
     force: yes
    when: ansible_os_family == 'Debian' 
...