---
- name: Install Jenkins
  hosts: localhost
  become: true
  
  tasks:

    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present

    - name: Add Jenkins Repo
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present
      
    - name: Install Jenkins  
      yum:
        name: jenkins
        state: present

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable Jenkins
      service:
        name: jenkins
        enabled: yes
        state: started
        

... 