---
- name: Build test
  hosts: WebCalcServers
  become: true
  
  tasks:

    - name: Build Maven project
      shell:
        cmd: |
          cd /home/centos/GroupWebCalc
          mvn test
      when: ansible_os_family == 'RedHat'
  
    - name: Build Maven project
      shell:
        cmd: |
          cd /home/ubuntu/GroupWebCalc
          mvn test
      when: ansible_os_family == 'Debian'

... 