---
- name: Deploy Web App to Tomcat
  hosts: WebCalcServers
  become: yes
  
  tasks:
    - name: Copy Web App WAR file
      copy:
        src: /Repo-dir/target/webapp.war
        dest: /opt/apache-tomcat-9.0.54/webapps
      when: ansible_os_family == 'RedHat'

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted

    
    - name: Start Tomcat Service
      shell: nohup /opt/apache-tomcat-9.0.54/bin/startup.sh &
      when: ansible_os_family == 'RedHat'

    - name: Start Tomcat Service
      shell: nohup /opt/apache-tomcat-9.0.54/bin/startup.sh &
      when: ansible_os_family == 'Debian'

... 