---
- name: Install and configure Tomcat
  hosts: tomcat_servers
  become: yes
  vars:
    tomcat_port: 8081

  tasks:
    - name: Update Tomcat server.xml to listen on a custom port
      lineinfile:
        path: /path/to/tomcat/conf/server.xml
        regexp: 'port="8080"'
        line: 'port="{{ tomcat_port }}"'
      notify: Restart Tomcat

  handlers:
    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
...

#
 - name: start tomcat
     when: ansible_facts['os_family']== "RedHat"
     command: sh '/opt/deploy/tomcatstartup.sh'
#

- name: Start Tomcat Service
      systemd:
        name: tomcat
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"


sudo /opt/apache-tomcat-9.0.54/bin/startup.sh